#!/bin/sh

[ "$(id -u)" != "0" ] && {
    echo "Please run as root" >&2
    exit 13 # EACCES
}

image_base="/boot/initramfs"
kernel_base="/boot/vmlinuz"

found="$(ls "${image_base}"-*.img)"
expected="$(ls "${kernel_base}"-* | sed "s%^${kernel_base}-\\(.*\\)$%${image_base}-\\1.img%g")"

# Remove uneeded
echo "${found}" | grep -Fxv "${expected}" | xargs -r -- rm -v >&2

# Check required
echo "${expected}" | grep -Fxv "${found}" | xargs -r -IEXPECTED -- echo "missing 'EXPECTED'" >&2
